name: Monitor
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
env:
  MULLED_NAMESPACE: jmchiltonorg
  GITHUB_USER: dockerhub-toolshed
jobs:
  monitor:
    name: Run planemo monitor
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8]
        subset:
         - repositories01.list
         - repositories02.list
         - repositories03.list
         - repositories04.list
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set github user
        run: |
          git config --global user.email "$GITHUB_USER@galaxyproject.org"
          git config --global user.name "$GITHUB_USER"
      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: 'https://${{env.GITHUB_USER}}:${{secrets.DOCKERHUB_TOOLSHED_WORKFLOWS}}@github.com/'
      - name: planemo monitor
        run: 'bash ./monitor.sh "${{ matrix.subset }}"'
        env:
          GITHUB_TOKEN: ${{ secrets.DOCKERHUB_TOOLSHED_WORKFLOWS }}
